Iter 5 P10: Frontend/userinfo
snuhcs-course/swpp-2023-project-team-18 pull request #109
Opened 2023-11-21 04:26 UTC by sungsung718

### PR Title:Iter 5 P10: Frontend/userinfo

#### PR Description: 
글자수를 카운트하는 코드를 넣을 때 한글이 자모가 분리되어서 입력되는 문제가 있습니다. 
제 로컬 문제인지 확인이 필요해서 draft로 올립니다.

#### Additional Comments:

2023-11-21 04:58 UTC, sungsung718 commented
한글 입력 문제 해결됐습니다

2023-11-21 07:19 UTC, footprinthere requested changes

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/fragment_userinfoview.xml
> +      android:textSize="15sp"
styles에 정의된 폰트 사용해주세요. 원하는 세팅이 없다면 새로 정의해주시면 되고요.

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewModel.java
> +    }
실제로는 String getter가 아니라 `LiveData`를 observe 하는 방식으로 구현될 것 같은데, 그건 이후에 처리하려고 하시는 건가요?

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewFragment.java
> +    private void updateUItoEditingMode() {
저는 state variable을 하나 관리하고 그것에 의존해 각 view의 상태가 결정되는 방식으로 설계하면 더 좋겠습니다. `ListFooterContainer`나 `BottomButtonContainer`를 참고해주세요.

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewFragment.java
> +        }
이 branch와 P20 중 뭐가 먼저 merge 될지는 모르겠지만, 이후에는 P20에서 구현된 `AuthenticationRepositoryFactory`를 사용하도록 수정되어야 할 것 같습니다.

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewFragment.java
> +    private void setCreatedAtText(FragmentUserinfoviewBinding binding, int digit) {
이건 그냥 색깔만 바꿔주는 것 같은데 실제로 "며칠"에 해당하는 숫자는 어떻게 넣어주는 거예요?

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/fragment_userinfoview.xml
> +    app:layout_constraintHorizontal_bias="0.55"
horizontal bias는 잘못 들어간 게 아닐까 싶은데, 의도된 건가요?

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/fragment_userinfoview.xml
아까 같이 봤던 버튼 누를 때마다 정렬 틀어지는 문제도 있었고, 전체적인 view 구조를 손봐야 하지 않을까 싶은데요.
* 여러 요소를 감싸고 있는 큰 네모 박스(`user_info_wrapper`)가 하나 있는데, 그게 왜 필요한지 잘 모르겠습니다. 또는 만약 필요하다고 하더라도, 별도 layout 파일로 정의해서 `include` 하는 방식으로 사용하면 좋겠습니다.
* 입력창과 버튼 아이콘, 밑줄을 묶어서 별도 layout으로 정의하고, horizontal margin을 주면 원하는 대로 쉽게 배치할 수 있지 않을까 싶습니다. 나머지 요소들은 vertical margin으로 위치를 설정할 수 있겠고요.

2023-11-21 07:19 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewFragment.java
> +    private void setCreatedAtText(FragmentUserinfoviewBinding binding, int digit) {
* `오늘까지 `와 ` 일째 하루를 남기고 있어요`를 String constant로 정의한 다음,
* 실제 날짜를 int로 받으면 A + int + B식으로 사이에 끼우고,
* digit을 변수로 받는 대신 알아서 전체 길이에서 B의 길이를 뺀 값을 `end`로 사용하면
더욱 편하지 않을까요? 그러면 string resource를 별도로 정의할 필요도 없어지고요.

2023-11-21 07:39 UTC, footprinthere commented
제가 대충 짜본 layout 구조입니다.
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.main_userinfoview.UserInfoViewFragment">

    <Button
        android:id="@+id/logout_button"
        style="@style/NORMAL_WHITE_BOLD"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/button"
        android:text="로그아웃"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.498"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/logo" />
    
    <ImageView
        android:id="@+id/logo"
        android:layout_width="200dp"
        android:layout_height="0dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHeight_percent="0.1"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/created_at_text"
        app:srcCompat="@drawable/text_logo" />
    
    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/nickname_edittext_container"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginHorizontal="40dp"
        android:layout_marginVertical="80dp"
        android:padding="5dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <EditText
            android:id="@+id/nickname_edittext"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:background="@null"
            android:fontFamily="@font/maruburi_bold"
            android:inputType="text"
            android:textSize="15sp"
            app:layout_constraintBottom_toTopOf="@id/border"
            app:layout_constraintEnd_toStartOf="@id/pen_icon"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <ImageButton
            android:id="@+id/pen_icon"
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:adjustViewBounds="true"
            android:background="@color/white"
            android:scaleType="centerInside"
            android:src="@drawable/pen"
            android:visibility="visible"
            app:layout_constraintBottom_toTopOf="@id/border"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.0"
            app:layout_constraintStart_toEndOf="@+id/nickname_edittext"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintVertical_bias="0.781" />

        <View
            android:id="@+id/border"
            android:layout_width="0dp"
            android:layout_height="1dp"
            android:background="@android:color/black"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/nickname_edittext" />

    </androidx.constraintlayout.widget.ConstraintLayout>
    
    <TextView
        android:id="@+id/nickname_length_warning_text"
        style="@style/SMALL_RED"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:text="@string/username_too_long"

        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/nickname_edittext_container"
        app:layout_constraintVertical_chainStyle="packed"
        app:layout_constraintWidth_percent="0.85" />

    <TextView
        android:id="@+id/created_at_text"
        style="@style/NORMAL_BLACK"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:bufferType="spannable"
        android:gravity="center"
        android:text="@string/created_at_text"

        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/nickname_length_warning_text" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

2023-11-21 07:41 UTC, sungsung718 commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewModel.java
> +    }
LiveData가 필요없을 것 같습니다. 로컬에 있는 걸 받아오는 거라 livedata로 state가 바뀌는 걸 계속 관찰할 필요가 없을 것 같습니다.

2023-11-21 08:04 UTC, footprinthere commented
햄버거 버튼 눌렀을 때 나오는 drawer에서 `로그아웃` 없애 주세요.

2023-11-21 08:23 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewModel.java
> +    }
이해했습니다!

2023-11-21 08:24 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/fragment_userinfoview.xml
> +    app:layout_constraintHorizontal_bias="0.55"
의도인 것 확인했습니다.

2023-11-21 10:53 UTC, footprinthere requested changes

2023-11-21 10:53 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/FragmentState.java
> +public class FragmentState {
이름을 좀 더 specific 하게 지어주세요.

2023-11-21 10:53 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_userinfoview/UserInfoViewFragment.java
> +    }
container를 별개의 class로 분리한 이상, fragment가 state를 보관할 필요는 없어 보입니다. 코드를 보면 어차피 state에 따라 달라지는 부분들은 전부 container 안에 있는 것 같네요.
- [ ] state를 container 안으로 넣고, fragment에서는 그냥 `container.updateUI()`를 바로 부르면 어떨까요?
- [ ] state를 바꾸는 함수의 경우 기존의 다른 container들에서 모두 `setState()`라는 이름을 쓰고 있기 때문에, 가능하면 이름을 통일했으면 좋겠습니다.

2023-11-21 10:53 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/user_info_wrapper.xml
> +    android:textSize="15sp"
`textSize` 옵션을 제거하고 style로 `NORMAL_BLACK_BOLD` 대신 `BIG_BLACK_BOLD`를 써야 하겠습니다.

2023-11-21 10:53 UTC, footprinthere commented on frontend/Moment/app/src/main/res/values/strings.xml
> +    <string name="created_at_text">오늘까지 12일째\n 하루를 남기고 있어요</string>
이건 이제 필요 없어지는 거죠?

2023-11-23 04:59 UTC, footprinthere approved these changes

2023-11-23 04:59 UTC, merged