Frontend/p11
snuhcs-course/swpp-2023-project-team-18 pull request #32
Opened 2023-10-20 13:13 UTC by sungsung718

### PR Title: UI implementation of Moment Write Page

#### PR Description: 
피그마에서 정한 스펙대로 전반적으로 구현하였으나 해결하지 못한 버그가 있습니다.
버그: 스크롤이 내려가서 두, 세번째 모먼트를 작성할 때쯤 키보드가 입력창까지 올라와서 쓰기 불편합니다.

2023-10-20 13:26 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/ListView_Item.java
> +public class ListView_Item {
얘랑 `ListView_Adapter`는 뭐 하는 애들인가요? 나중에 설명해주세용

2023-10-20 13:30 UTC, footprinthere requested changes
코드 formatter 적용해주시면 좋겠습니다.

2023-10-20 13:30 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/WriteViewFragment.java
> +        // TODO : 여기부터 slide가 가능해짐
TODO 내용은 다음 iter 때 하게 되는 건가요? 그러면 추가로 인수인계가 필요할 것 같아요.

2023-10-20 13:30 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/fragment_writeview.xml
> +    android:layout_marginTop="60dp"
실행해봤을 때 60dp가 실제 상단바보다 두껍다고 느껴지는데, 괜찮은 건가요? 제가 슬랙에 올려드린 대로 변수로 설정하는 게 어떨까요?

2023-10-20 13:30 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/tmp.xml
tmp나 test가 들어가는 파일들은 뭔지도 설명이 필요해 보입니다.

2023-10-20 13:44 UTC, aylee2008 commented
수고하셨습니다! 저 버그는 조금 귀찮은 정도고 심각한 건 아니라 일단은 넘어가고 api 연결을 하는 게 좋을 것 같고,
다만 ui 구현에서 슬라이드 시 날짜가 바뀌는 건 구현되어 있어야 한다고 생각해서,
슬라이드 했을 때 header 부분에 날짜가 변경되는 것만 더 구현해서 올려주세요~

2023-10-20 13:53 UTC, footprinthere requested changes

2023-10-20 13:53 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/DaySlide/TodayViewFragment.java
> +    private int MAX_LENGTH = 100;
`final`로 하면 더 좋겠고요.
모먼트 자수 제한은 1000자로 얘기했던 것 같습니다.

2023-10-20 13:53 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/DaySlide/TodayViewFragment.java
> +        // 이건 submit button 누르면 키보드 사라지게
아래쪽에 이어지는 코드는 add 버튼을 눌렀을 때의 동작에 관한 것 같은데, 잘못된 주석인가요?

2023-10-20 13:53 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/DaySlide/TodayViewFragment.java
> +            // 아래 줄 있으면, 텍스트 입력이 박스 넘어가도 줄바꿈이 안됨
이건 불필요한 거라면 지우는 게 덜 헷갈릴 것 같아요.

2023-10-20 13:53 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/DaySlide/TodayViewFragment.java
> +                imm.hideSoftInputFromWindow(getActivity().getCurrentFocus().getWindowToken(), 0);
`KeyboardUtils`에 이 기능을 하는 함수를 구현해두신 듯한데, 그걸 쓰는 게 더 좋을 것 같아요.

2023-10-21 01:26 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/listview_footer.xml
> +            android:layout_height="@dimen/editTextHeight"
height는 `wrap_content`로 주고 `minLines=5` 같은 옵션을 주면 어떨까요? 저렇게 height를 숫자로 설정해버리면 이전의 `회원가입` 텍스트버튼처럼 화면 크기에 따라 어떻게 표시될지를 예측하기가 어렵고, 또 무엇보다 텍스트가 길어지면 입력창 내에서 스크롤을 해야 하게 됩니다.

2023-10-21 01:26 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/listview_footer.xml
> +            android:visibility="gone"
기본적으로 안 보이는 view를 만들었을 때, `tools:visibility="visible"` 옵션을 주면 안드로이드 스튜디오의 Design 화면에서는 보이도록 설정할 수 있습니다.

2023-10-21 15:28 UTC, aylee2008 commented
p12에서 p11을 함께 처리하기로 했으므로 이 pr은 닫겠습니다~

2023-10-21 15:28 UTC, closed without merging