backend/hashtag fix: Fix Hashtag View
snuhcs-course/swpp-2023-project-team-18 pull request #67
Opened 2023-11-03 12:26 UTC by impri2

### PR Title: Fix Hashtag View

#### PR Description: 
중복된 Hashtag Model 객체를 만들지 않도록 수정했습니다.
hashtag view GET 시 story id 대신 start, end timestamp를 받도록 수정했습니다.
#### Additional Comments: 
None

2023-11-03 12:33 UTC, aylee2008 commented
엇 그런데 hashtag story_id로 받아오는 건 있어야 하지 않나요? 그걸 없애신 것 같아서요. 그게 없으면 이전 날짜로 슬라이드할 때 hashtag 받아올 수가 없을 것 같은데요?

2023-11-03 12:35 UTC, impri2 commented
> 엇 그런데 hashtag story_id로 받아오는 건 있어야 하지 않나요? 그걸 없애신 것 같아서요. 그게 없으면 이전 날짜로 슬라이드할 때 hashtag 받아올 수가 없을 것 같은데요?

어 날짜로 timestamp 계산해서 hashtag 받아오면 될거라고 생각했는데 다시 만들까요?

2023-11-03 13:44 UTC, aylee2008 commented
아하 일리가 있네요. 그럼 story_id로 받아오는 api는 필요 없겠군요.
그런데 hashtag에서 story로 접근이 가능하도록 코드가 짜여져 있나요? 뭔가 hashtag 검색할 때 필요하지 않을까.. 어렴풋하게 생각이 들긴 하는데 그건 검색 api 구현할 때 같이 생각하면 되겠죠?

2023-11-03 14:09 UTC, impri2 commented
manytomanyfield는 양방향으로 filter 가능합니다

2023-11-03 14:52 UTC, footprinthere requested changes

2023-11-03 14:52 UTC, footprinthere commented on backend/moment/writing/views.py
> +        hashtags = Hashtag.objects.filter((date_condition & user_condition)).distinct()
`distinct()`는 중복 제거해주는 역할인 것 같은데, 저장할 때 어차피 걸러줄 거라면 여기서는 사실상 필요 없는 거죠?

2023-11-03 14:52 UTC, footprinthere commented on backend/moment/writing/views.py
>              if hashtag.strip() is not ""
* 문자열 비교는 `!=`로 고쳐주세요.
* 띄어쓰기 얘기는 모였을 때 한번 해보기로 해요.

2023-11-03 14:52 UTC, footprinthere commented on backend/moment/writing/views.py
> +                curr_hashtag = Hashtag.objects.get(content=hashtag)
우선 `get` 한 다음 에러가 뜨면 없다고 판단해서 다시 생성하는 식인 것 같은데, 에러를 일으키는 대신 그냥 있는지 확인해서 boolean을 주는 함수는 없나요?

2023-11-03 15:10 UTC, impri2 commented on backend/moment/writing/views.py
> +        hashtags = Hashtag.objects.filter((date_condition & user_condition)).distinct()
아니요 이거 제거하면 test_get_hashtags_success테스트 실패합니다. 여러 스토리가 참조하는 해시태그가 중복으로 불러와져요.

2023-11-03 15:21 UTC, footprinthere commented
story GET api 스펙이 바뀌는 건가요? 가능하면 최대한 안 바뀌는 선에서 해결되면 좋겠다 싶긴 합니다.

2023-11-03 15:23 UTC, impri2 commented
> story GET api 스펙이 바뀌는 건가요? 가능하면 최대한 안 바뀌는 선에서 해결되면 좋겠다 싶긴 합니다.

story_id 대신 start end 쓰는 걸로 바뀌었습니다. 혹시 지금 쓰고 있는 곳이 있나요? 지금은 쓰기 탭에서 story view로 한꺼번에 받아와서 상관없을 거라고 생각했어요

2023-11-03 15:24 UTC, impri2 commented on backend/moment/writing/views.py
> +                curr_hashtag = Hashtag.objects.get(content=hashtag)
get_or_create 함수로 바꿨습니다

2023-11-03 15:24 UTC, impri2 commented on backend/moment/writing/views.py
>              if hashtag.strip() is not ""
!=로 수정했습니다

2023-11-04 02:12 UTC, impri2 commented on backend/moment/writing/views.py
>              if hashtag.strip() is not ""
정규식 사용해서 수정했습니다.

2023-11-04 02:26 UTC, footprinthere commented on backend/moment/writing/views.py
> +        hashtags = Hashtag.objects.filter((date_condition & user_condition)).distinct()
스토리 하나에는 중복된 태그가 여러 개 들어가지 않지만, 스토리 여러 개를 모으게 되면 중복이 있을 수도 있다는 말이죠?

2023-11-04 02:28 UTC, impri2 commented on backend/moment/writing/views.py
> +        hashtags = Hashtag.objects.filter((date_condition & user_condition)).distinct()
넵

2023-11-04 02:35 UTC, impri2 commented on backend/moment/writing/views.py
> +        hashtags = Hashtag.objects.filter((date_condition & user_condition)).distinct()
객체는 하나여도 filter하면 여러개를 가져오는 경우가 있는 것 같아요

2023-11-04 07:32 UTC, aylee2008 commented
hashtag도 blank 입력 가능하도록 변경 부탁드려요~ 참고: #71

2023-11-05 01:04 UTC, footprinthere approved these changes
좋습니당

2023-11-05 02:59 UTC, redcourage commented
확인했습니다.

2023-11-05 02:59 UTC, merged