Frontend/P23: 넛지 UI 구현
snuhcs-course/swpp-2023-project-team-18 pull request #76
Opened 2023-11-07 15:21 UTC by footprinthere

### Frontend/P23: 넛지 UI 구현

#### PR Description: 
* 넛지 UI를 구현하는 layout xml과 `NudgeHeaderContainer` class를 구현했습니다.
* 넛지 UI는 `TodayViewFragment`에 들어 있는 ListView에 header로 포함됩니다.
* `NudgeUiState`를 구현하고 UiState에 담긴 데이터로 view를 업데이트하는 부분까지 구현해놓았습니다.

#### Additional Comments: 
* 정헌님이 올려주신 `TodayViewFragment` 날짜 표시 문제 해결 PR로부터 출발해서 그 내용이 들어 있습니다.

2023-11-08 08:45 UTC, footprinthere commented
디자인 수정했습니다.

2023-11-09 11:49 UTC, sungsung718 requested changes

2023-11-09 11:49 UTC, sungsung718 commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/NudgeHeaderContainer.java
> +        // TODO: GONE 처리 후에도 리스트 위쪽에 공간이 남아 있는 문제 해결
여기는 해결된 문제인 듯해서 주석 지워주세요~

2023-11-09 11:58 UTC, sungsung718 approved these changes

2023-11-09 11:58 UTC, merged