Frontend/p15: 디자인 다듬기
snuhcs-course/swpp-2023-project-team-18 pull request #98
Opened 2023-11-18 08:17 UTC by impri2

### PR Title: 디자인 다듬기

#### PR Description: 
감정 선택 뷰, 폰트 크기, 모먼트 체크 버튼 크기 수정했습니다.
#### Additional Comments: 
None

2023-11-18 08:37 UTC, footprinthere requested changes
* submit 버튼을 단순히 키우기만 하는 게 아니라 **add 버튼과 동일한 위치에 배치하기로** 합의했었습니다. 잘못된 구현이니 수정해주세요.

**그 외 의견**
* 폰트 저는 작은 게 더 좋은 것 같습니다. 다른 분들 의견 받고 결정합시다.
* emotion container의 디자인이... 제가 생각한 것과 많이 다릅니다.
  - 애초에 디자인을 바꾸기로 결정했던 이유가 '버튼 같아 보이지 않아서'였는데, 그런 측면에서 딱히 개선되지 않은 것 같습니다.
  - **그림이 너무 작고 글자가 너무 큽니다.** 저는 버튼 같아 보이려면 글자 하나보다 그림이 더 커야 한다고 생각합니다. 가로 폭이 좁아 어려우면 2x5 말고 5x2로 세로로 길게 배열하는 것도 나쁘지 않다고 생각합니다.
* emotion container의 구조 자체가 최선인지 잘 모르겠습니다. 저라면 **[그림 하나 + label 하나]로 이루어진 ConstraintLayout 기반 layout을** 정의하고, 2x5 (또는 5x2) grid 안에 그걸 하나씩 배치할 것 같습니다. 그림과 텍스트는 코드에서 dynamic 하게 설정하고요.

2023-11-18 08:37 UTC, footprinthere commented on frontend/Moment/app/src/main/res/layout/emotion_grid.xml
> +  <!-- Text 1 -->
주석이 잘못 들어간 것 같아요. 다시 점검해주세요.

2023-11-18 08:37 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/EmotionGridContainer.java
> +            imageView.setOnClickListener(v -> {
복붙 말고... 함수로 만들어 씁시다.

2023-11-18 08:43 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/EmotionGridContainer.java
> +            imageView.setOnClickListener(v -> {
또는 내용이 완전히 동일하다면 `OnClickListener` 객체 하나를 만들고 그걸 양쪽에 등록하는 방법도 있겠습니다.

2023-11-18 16:44 UTC, redcourage commented
1. 버튼의 느낌을 줄 수 있도록 해당 view를 수정했습니다.
- 기존 GridLayout은 유지하면서, <감정아이콘, 감정이름>을 하나의 LinearLayout으로 감싸고, LinearLayout의 style에 테두리를 주었습니다.
2. 각 LinearLayout과 ImageView에 Clickable 속성을 적용하고, onClickListener를 등록하여 버튼과 동일한 효과가 나도록 했습니다.
3. 특히 감정을 눌렀을 때 테두리와 이미지도 모두 빨간색으로 변하도록 로직을 추가하였습니다.
4. 마무리 이후에는 감정 선택이 안되도록 기존의 freeze 함수에 linearLayout과 ImageView 의 setClickable을 textview와 동일하게 로직을 추가하였습니다

2023-11-19 00:09 UTC, footprinthere requested changes
* 감정 아이콘이 일부만 표시되는 문제가 있습니다. (슬랙에 스크린샷 올려두었습니다.)
---
* `모먼트 제출`이라는 텍스트는 수정하면 좋겠습니다.
* 폰트 크기도 의견 정해지면 반영해주세요.

2023-11-19 00:09 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/EmotionContainer.java
> +        for (int i = 0; i < linearLayoutList.size(); i++) {
OnClickListener를 그냥 가장 바깥쪽에 해당하는 LinearLayout에만 등록해도 될 것 같아요. 그러면 `freeze()`에서도 이미지와 텍스트를 일일이 순회할 필요가 없고요. 그렇게 안 되던가요?

2023-11-19 06:21 UTC, footprinthere requested changes

2023-11-19 06:21 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/BottomButtonContainer.java
> +                    // 태그 입력값 가져오기
이 코드가 들어갈 자리가 여기가 아닌 것 같습니다. 이건 `점수 저장하기` 버튼의 동작을 지정하는 부분입니다.
그리고 이 코드가 무얼 하고 있는 것인지 잘 모르겠습니다. API 호출 전에 입력된 string을 변경하려고 하는 건가요? 지금 코드만 봤을 때는 `String tagInput`을 가져온 뒤 그냥 수정하기만 하고 있는데, 이렇게 하면 아무런 영향이 없을 것 같습니다.

2023-11-19 06:24 UTC, footprinthere commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/BottomButtonContainer.java
> +                    // 태그 입력값 가져오기
* 서버 쪽에서 아마 이런 케이스를 처리해줄 테지만,  프론트에서 한번 걸러주는 것도 좋다고 생각하긴 합니다.
* 만약 구현할 거라면 저는 `ListFooterContainer.getTagInput()` 안에서 처리하고, 바깥으로 꺼내지는 않았으면 좋겠습니다.

2023-11-19 06:28 UTC, redcourage commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/BottomButtonContainer.java
> +                    // 태그 입력값 가져오기
코멘트 주신 코드는 마지막 commit에서 삭제되어있을건데 한번 확인부탁드립니다

2023-11-19 09:27 UTC, redcourage commented on frontend/Moment/app/src/main/java/snu/swpp/moment/ui/main_writeview/component/EmotionContainer.java
> +        for (int i = 0; i < linearLayoutList.size(); i++) {
이거 LinearLayout만 등록하면 텍스트나 이미지 터치했을때는 클릭이 안되어서 각 요소들에 모두 onClickListener를 등록해두었습니다. 터치되는 영역이 테두리와 글자 이미지를 제외한 영역인것으로 추정되는데 이미지 텍스트 터치하면 반응이 안돼서 모두 등록해두었습니다

2023-11-19 09:39 UTC, footprinthere approved these changes

2023-11-19 10:41 UTC, merged